CREATE TABLE user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_type_id BIGINT NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(50) NULL,
    tax_id VARCHAR(50) NULL,
    address VARCHAR(300) NULL,
    city VARCHAR(100) NULL,
    postal_code VARCHAR(20) NULL,
    country VARCHAR(100) NULL,
    language_id BIGINT NULL,
    business_partner_id BIGINT NULL,
    provider_id BIGINT NULL,
    discount DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_type_id) REFERENCES user_type(id),
    FOREIGN KEY (language_id) REFERENCES language(id),
    FOREIGN KEY (business_partner_id) REFERENCES business_partner(id),
    FOREIGN KEY (provider_id) REFERENCES provider(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
