CREATE TABLE reservation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reservation_code VARCHAR(20) NOT NULL UNIQUE,
    status_id BIGINT NOT NULL,
    booked_by_user_id BIGINT NOT NULL,
    owner_user_id BIGINT NULL,
    owner_first_name VARCHAR(100) NOT NULL,
    owner_last_name VARCHAR(100) NOT NULL,
    owner_email VARCHAR(200) NULL,
    owner_phone VARCHAR(50) NULL,
    owner_tax_id VARCHAR(50) NULL,
    owner_address VARCHAR(300) NULL,
    owner_city VARCHAR(100) NULL,
    owner_postal_code VARCHAR(20) NULL,
    owner_country VARCHAR(100) NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    tax_amount DECIMAL(10, 2) NOT NULL,
    margin_amount DECIMAL(10, 2) NOT NULL,
    discount_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    total_price DECIMAL(10, 2) NOT NULL,
    currency_id BIGINT NOT NULL,
    exchange_rate_id BIGINT NOT NULL,
    promo_code_id BIGINT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (status_id) REFERENCES reservation_status(id),
    FOREIGN KEY (booked_by_user_id) REFERENCES user(id),
    FOREIGN KEY (owner_user_id) REFERENCES user(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (exchange_rate_id) REFERENCES exchange_rate(id),
    FOREIGN KEY (promo_code_id) REFERENCES promo_code(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
