CREATE TABLE reservation_line (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    hotel_provider_room_type_id BIGINT NOT NULL,
    board_type_id BIGINT NOT NULL DEFAULT 1,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    num_rooms INT NOT NULL DEFAULT 1,
    num_guests TINYINT NOT NULL,
    price_per_night DECIMAL(10, 2) NOT NULL,
    board_price_per_night DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    num_nights INT NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    tax_amount DECIMAL(10, 2) NOT NULL,
    margin_amount DECIMAL(10, 2) NOT NULL,
    discount_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    total_price DECIMAL(10, 2) NOT NULL,
    currency_id BIGINT NOT NULL,
    exchange_rate_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (reservation_id) REFERENCES reservation(id),
    FOREIGN KEY (hotel_provider_room_type_id) REFERENCES hotel_provider_room_type(id),
    FOREIGN KEY (board_type_id) REFERENCES board_type(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
